In [1]:
import pandas as pd
import numpy as np
from numpy import nan as NA

In [2]:
df=pd.DataFrame(np.random.randn(7,3))
df.iloc[:2,1]=NA
df.iloc[:3,2]=NA
df

          0         1         2
0 -1.234578       NaN       NaN
1 -0.273299       NaN       NaN
2  2.179173 -0.043947       NaN
3 -1.128843 -0.111913 -0.070412
4  0.127468 -0.261540  1.117033
5  1.920710  0.193494 -1.511366
6 -0.839844 -1.040095  0.819620

In [3]:
df.fillna(df.mean())

          0         1         2
0 -1.234578 -0.252800  0.088719
1 -0.273299 -0.252800  0.088719
2  2.179173 -0.043947  0.088719
3 -1.128843 -0.111913 -0.070412
4  0.127468 -0.261540  1.117033
5  1.920710  0.193494 -1.511366
6 -0.839844 -1.040095  0.819620

In [4]:
data=pd.DataFrame({'k1':['one','two']*3+['two'],
                  'k2':[1,1,2,3,3,4,4]})
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [5]:
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [6]:
data['x1']=range(7)

In [7]:
data.drop_duplicates(['k1','k2'])

    k1  k2  x1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5

In [8]:
_k2=list(data['k2'])

In [9]:
group=['a','b','c']
bins=[0,2,4,6]
cats=pd.cut(_k2,4)
cats

[(0.997, 1.75], (0.997, 1.75], (1.75, 2.5], (2.5, 3.25], (2.5, 3.25], (3.25, 4.0], (3.25, 4.0]]
Categories (4, interval[float64, right]): [(0.997, 1.75] < (1.75, 2.5] < (2.5, 3.25] < (3.25, 4.0]]

In [10]:
ki=pd.DataFrame(np.random.randn(500,4))
ki.describe()

                0           1           2           3
count  500.000000  500.000000  500.000000  500.000000
mean    -0.051485   -0.060156   -0.017919    0.003932
std      0.989623    1.005855    1.001080    0.978213
min     -2.802795   -2.593108   -3.112969   -2.887447
25%     -0.754539   -0.813186   -0.731351   -0.602677
50%      0.009651   -0.092358    0.034455   -0.016697
75%      0.627762    0.607810    0.704964    0.681337
max      2.914149    2.581731    2.723727    3.215975

In [11]:
k2=ki[2]
np.abs(k2)>2

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Name: 2, Length: 500, dtype: bool

In [12]:
np.sign(ki)

       0    1    2    3
0   -1.0 -1.0  1.0 -1.0
1   -1.0  1.0  1.0  1.0
2   -1.0 -1.0 -1.0  1.0
3   -1.0  1.0  1.0  1.0
4   -1.0 -1.0  1.0  1.0
..   ...  ...  ...  ...
495 -1.0  1.0 -1.0 -1.0
496  1.0  1.0 -1.0  1.0
497  1.0  1.0 -1.0 -1.0
498  1.0  1.0  1.0 -1.0
499  1.0  1.0  1.0  1.0

[500 rows x 4 columns]

In [13]:
ki

            0         1         2         3
0   -0.984956 -0.093757  1.042002 -0.396306
1   -2.404895  0.092640  0.957782  0.672287
2   -2.341263 -1.180618 -1.661358  0.123878
3   -1.538941  0.659799  1.369444  0.662556
4   -0.607887 -0.376018  0.864161  0.235323
..        ...       ...       ...       ...
495 -0.168444  0.510424 -0.646472 -1.777910
496  0.885454  1.030238 -0.061852  0.639976
497  0.164238  0.689110 -0.607777 -0.555337
498  2.623215  0.227815  0.414901 -1.092551
499  0.042881  0.783803  1.674697  0.535864

[500 rows x 4 columns]

In [14]:
qe=pd.DataFrame(np.arange(5*4).reshape(5,4)) 
sampler=np.random.permutation(5)

In [15]:
qe

    0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [16]:
sampler

array([1, 2, 3, 4, 0], dtype=int32)

In [17]:
qe.iloc[sampler]

    0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19
0   0   1   2   3

In [18]:
qe.take(sampler)

    0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19
0   0   1   2   3

In [19]:
qe.sample(n=3)

    0   1   2   3
3  12  13  14  15
2   8   9  10  11
4  16  17  18  19

In [20]:
val='a,b,   go'
pieces=[x.strip() for x in val.split(',')]
pieces

['a', 'b', 'go']

In [21]:
'::'.join(pieces)

'a::b::go'

In [22]:
Data=pd.Series(np.random.randn(9),
              index=[['a','a','b','b','c','c','v','k','l'],
                    [1,2,3,1,3,1,2,2,3]])
Data

a  1   -1.050634
   2   -0.570420
b  3   -0.474511
   1    1.235876
c  3    0.090629
   1    1.274185
v  2   -0.147187
k  2   -0.249297
l  3    0.971980
dtype: float64

In [23]:
Data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 3),
            ('b', 1),
            ('c', 3),
            ('c', 1),
            ('v', 2),
            ('k', 2),
            ('l', 3)],
           )

In [24]:
Data.unstack().fillna(0)

          1         2         3
a -1.050634 -0.570420  0.000000
b  1.235876  0.000000 -0.474511
c  1.274185  0.000000  0.090629
k  0.000000 -0.249297  0.000000
l  0.000000  0.000000  0.971980
v  0.000000 -0.147187  0.000000

In [25]:
data = pd.Series(np.random.uniform(size=9),
                 index=[["a", "a", "a", "b", "b", "c", "c", "d", "d"],
                        [1, 2, 3, 1, 3, 1, 2, 2, 3]])
data

a  1    0.729323
   2    0.809534
   3    0.843100
b  1    0.263090
   3    0.484619
c  1    0.997930
   2    0.387357
d  2    0.764221
   3    0.491354
dtype: float64

In [26]:
df3 = pd.DataFrame({"lkey": ["b", "b", "a", "c", "a", "a", "b"],
                    "data1": pd.Series(range(7), dtype="Int64")})
df4 = pd.DataFrame({"rkey": ["a", "b", "d"],
                    "data2": pd.Series(range(3), dtype="Int64")})
pd.merge(df3, df4, left_on="lkey", right_on="rkey")

  lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    a      2    a      0
3    a      4    a      0
4    a      5    a      0
5    b      6    b      1

In [27]:
pd.merge(df3, df4, left_on="lkey", right_on="rkey", how="outer")

  lkey  data1 rkey  data2
0    a      2    a      0
1    a      4    a      0
2    a      5    a      0
3    b      0    b      1
4    b      1    b      1
5    b      6    b      1
6    c      3  NaN   <NA>
7  NaN   <NA>    d      2

In [31]:
a=pd.Series([np.nan,2.5,0.0,3.5,4.5,np.nan],
           index=['f','e','d','c','b','a'])
b=pd.Series([0.0,2.0,0.0,3.5,4.5,np.nan],
           index=['a','b','c','d','e','f'])
a

f    NaN
e    2.5
d    0.0
c    3.5
b    4.5
a    NaN
dtype: float64

In [32]:
np.where(pd.isnull(a),b,a)

array([0. , 2.5, 0. , 3.5, 4.5, nan])

In [34]:
a.combine_first(b)

a    0.0
b    4.5
c    3.5
d    0.0
e    2.5
f    NaN
dtype: float64