In [13]:
%run "D:\\program p\\secondly code\\a function code for test.ipynb"
print(result)

(300, 3, 10, 5, 2)

In [11]:
fx(2,3,4,5)

120

In [16]:
test0=1,2,3,4,5
test1=((1,2,3),(1,2,4),(4,3,2))
test1

((1, 2, 3), (1, 2, 4), (4, 3, 2))

In [12]:
tuple(result)

(300, 3, 10, 5, 2)

In [17]:
for a,b,c in test1:
    print('a{0} b{1} c{2}'.format(a,b,c))

a1 b2 c3
a1 b2 c4
a4 b3 c2

In [40]:
a,b,*_=test1
print('{0}{1}{2}'.format(a,b,*_))

(1, 2, 3)(1, 2, 4)(4, 3, 2)

In [41]:
d=[a,b]
d.append('k')
d.insert(1,'bee')
print(d)

[(1, 2, 3), 'bee', (1, 2, 4), 'k']

In [47]:
print(d.pop(1))
print(d)
q=[1]
d1=d.extend(q)
print(d)

10
[(1, 2, 3), 5, 2, 1, 1, 1]
[(1, 2, 3), 5, 2, 1, 1, 1, 1]

In [1]:
dickion={'a':1,'b':2,'c':4}

In [2]:
print(dickion)

{'a': 1, 'b': 2, 'c': 4}

In [2]:
import numpy as np

In [12]:
data=np.random.randn(2,3)
print(data)

[[-0.53789932 -0.14778472 -0.99915178]
 [ 0.10843014  0.30700648 -0.81077597]]

In [6]:
data=data*10
data

array([[ 19.2929817 , -20.62981542,   6.96060126],
       [ -9.36581612,  -4.7158241 ,  -6.43069965]])

In [38]:
data.shape

In [5]:
data2=[[1,2,3,4],[2,3,4,6],[23,24,25,26],[12,23,34,45]]
arr2=np.array(data2)
arr2

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  6],
       [23, 24, 25, 26],
       [12, 23, 34, 45]])

In [6]:
re=arr2*arr2
re

array([[   1,    4,    9,   16],
       [   4,    9,   16,   36],
       [ 529,  576,  625,  676],
       [ 144,  529, 1156, 2025]])

In [7]:
arr_slice=arr2[0:1]
(arr_slice[0])[2]=10
arr2

array([[ 1,  2, 10,  4],
       [ 2,  3,  4,  6],
       [23, 24, 25, 26],
       [12, 23, 34, 45]])

In [8]:
arr2[2][3]=2
arr2

array([[ 1,  2, 10,  4],
       [ 2,  3,  4,  6],
       [23, 24, 25,  2],
       [12, 23, 34, 45]])

In [9]:
arr2[:2,0:2]

array([[1, 2],
       [2, 3]])

In [10]:
names=np.array(['bob','dan','alan','ben'])

arr2[names=='dan']=0
arr2

array([[ 1,  2, 10,  4],
       [ 0,  0,  0,  0],
       [23, 24, 25,  2],
       [12, 23, 34, 45]])

In [11]:

np.dot(arr2.T,arr2)

array([[ 674,  830,  993,  590],
       [ 830, 1109, 1402, 1091],
       [ 993, 1402, 1881, 1620],
       [ 590, 1091, 1620, 2045]])

In [14]:
test0=np.arange(10)
names=='dan'

array([False,  True, False, False])

In [13]:
np.sqrt(test0)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [3]:
test1=np.random.randn(3,3)
print(test1)
print(np.where(test1>0,1,-1))
k=np.where(test1>0,1,-1)
np.save("C:\\Users\\Yyx_2\\Desktop\\code\\data.npy",k)

[[-0.85320269 -0.06501112 -1.02442754]
 [-0.086094    1.12687976  0.38495609]
 [ 0.73866585  0.72132424 -1.9456398 ]]
[[-1 -1 -1]
 [-1  1  1]
 [ 1  1 -1]]

In [1]:
import pandas as pd
from pandas import Series,DataFrame
a=pd.Series(['ben','a','kim','tom'],index=['a','b','c','d'])
a2=pd.Series([1,-2,3,-4])
a2[a2>0]

0    1
2    3
dtype: int64

In [2]:
a['a']

'ben'

In [3]:
b={1:'a',2:'b',3:'c'}
B=pd.Series(b)
B

1    a
2    b
3    c
dtype: object

In [4]:
data2={'state':['ohio','ohio','ohio','nevada','nevada'],
      'year':[2012,2013,2014,2012,2013],
      'pop':[1.2,1.7,1.6,1.5,1.4]}
frame=pd.DataFrame(data2)
frame

    state  year  pop
0    ohio  2012  1.2
1    ohio  2013  1.7
2    ohio  2014  1.6
3  nevada  2012  1.5
4  nevada  2013  1.4

In [5]:
frame.loc[[0,1,2,3]]

    state  year  pop
0    ohio  2012  1.2
1    ohio  2013  1.7
2    ohio  2014  1.6
3  nevada  2012  1.5

In [6]:
frame.reindex([0,1,2,3,4,5],columns=['year','pop','state'])

     year  pop   state
0  2012.0  1.2    ohio
1  2013.0  1.7    ohio
2  2014.0  1.6    ohio
3  2012.0  1.5  nevada
4  2013.0  1.4  nevada
5     NaN  NaN     NaN

In [7]:
new_frame=frame.drop('pop',axis=1)
print(new_frame)
print(frame)

    state  year
0    ohio  2012
1    ohio  2013
2    ohio  2014
3  nevada  2012
4  nevada  2013
    state  year  pop
0    ohio  2012  1.2
1    ohio  2013  1.7
2    ohio  2014  1.6
3  nevada  2012  1.5
4  nevada  2013  1.4

In [8]:
frame.loc[[0,1,2],'year']

0    2012
1    2013
2    2014
Name: year, dtype: int64

In [9]:
frame.sum()

state    ohioohioohionevadanevada
year                        10064
pop                           7.4
dtype: object