In [20]:
import pandas as pd
import numpy as np

data=pd.DataFrame(np.arange(6).reshape((2,3)),
     index=pd.Index(['Alla','Babo'],name='AB'),
     columns=pd.Index(['one','two','three'],
                name='number'))
data

number  one  two  three
AB
Alla      0    1      2
Babo      3    4      5

In [24]:
ki=data.stack()
ki

AB    number
Alla  one       0
      two       1
      three     2
Babo  one       3
      two       4
      three     5
dtype: int64

In [29]:
kd=ki.unstack('AB')#kd=ki.unstack(0)效果相同
kd

AB      Alla  Babo
number
one        0     3
two        1     4
three      2     5

In [30]:
s1=pd.Series([0,1,2,3],index=['a','b','c','d'])
s2=pd.Series([4,5,6],index=['c','d','e'])
data1=pd.concat([s1,s2],keys=['A','B'])
data1

A  a    0
   b    1
   c    2
   d    3
B  c    4
   d    5
   e    6
dtype: int64

In [38]:
ki1=data1.unstack()
ki1#缺失值的产生

     a    b    c    d    e
A  0.0  1.0  2.0  3.0  NaN
B  NaN  NaN  4.0  5.0  6.0

In [37]:
kd1=ki1.stack()
kd1#可逆的，缺失值的省略

A  a    0.0
   b    1.0
   c    2.0
   d    3.0
B  c    4.0
   d    5.0
   e    6.0
dtype: float64

In [44]:
kd1_1=data1.unstack().stack(future_stack=True)#kd1_1=data1.unstack().stack(dropna=False)保留na，但是这个用法好像更新了
kd1_1

A  a    0.0
   b    1.0
   c    2.0
   d    3.0
   e    NaN
B  a    NaN
   b    NaN
   c    4.0
   d    5.0
   e    6.0
dtype: float64

In [57]:
di_0=pd.DataFrame({'left0':ki,'right0':ki-2},
               columns=pd.Index(['left0','right0'],name='side'))
di_0

side         left0  right0
AB   number
Alla one         0      -2
     two         1      -1
     three       2       0
Babo one         3       1
     two         4       2
     three       5       3

In [58]:
di_1=pd.DataFrame({'left':ki,'right':ki-2},
               columns=pd.Index(['left0','right0'],name='side'))
di_1#参考不对应的情况（be like:left0和left）

Empty DataFrame
Columns: [left0, right0]
Index: []

In [65]:
di_0.unstack('AB')#堆叠后变为最低层级

side   left0      right0
AB      Alla Babo   Alla Babo
number
one        0    3     -2    1
two        1    4     -1    2
three      2    5      0    3

In [66]:
di_0.unstack('AB').stack('side')#指出堆叠的轴向（side）

C:\Users\Yyx_2\AppData\Local\Temp\ipykernel_13748\1729837781.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  di_0.unstack('AB').stack('side')#指出堆叠的轴向（side）

AB             Alla  Babo
number side
one    left0      0     3
       right0    -2     1
two    left0      1     4
       right0    -1     2
three  left0      2     5
       right0     0     3

In [67]:
di_1.unstack()

Series([], dtype: float64)